apiVersion: api.omer.aplatony/v1alpha1
kind: DeathTimer
metadata:
  labels:
    app.kubernetes.io/name: deathtimer
    app.kubernetes.io/instance: deathtimer-sample
    app.kubernetes.io/part-of: death-timer-contoller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: death-timer-contoller
  name: deathtimer-sample
spec:
  namespaces:
    - name: demo1
      date: "2021-11-22T15:30:45"
    - name: demo2
      date: "2021-11-22T15:30:45"
    - name: demo3
      date: "2021-11-22T15:30:45"
    - name: omer
      date: "2021-11-22T15:30:45"
  deployments:
    - name: deployment1
      date: "2021-11-22T15:30:45"
      namespace: demo-deployment1
    - name: deployment2
      date: "2021-11-22T15:30:45"
      namespace: demo-deployment2
  pods:
    - name: pod1
      date: "2021-11-22T15:30:45"
      namespace: demo-pod1
    - name: pod2
      date: "2021-11-22T15:30:45"
      namespace: demo-pod2
